import type { Scholarship } from "./types";

export const SCHOLARSHIPS: Scholarship[] = [
  {
    id: 1,
    type: "Стипендия",
    title: "Полная стипендия Оксфордского университета",
    desc: "Подайте заявку на полную стипендию Оксфордского университета. Покрывает обучение, проживание и расходы на жизнь.",
    institution: "Оксфордский университет",
    daysLeft: 14,
    hoursLeft: 23,
    minutesLeft: 45,
    documents: ["Личное эссе", "Рекомендательное письмо", "Академическая выписка", "Резюме"],
    requiredFiles: [
      { icon: "📄", name: "kopiya_pasporta.pdf" },
      { icon: "💰", name: "finansovaya_spravka.pdf" },
      { icon: "🌐", name: "yazykovoy_sertifikat.pdf" },
    ],
  },
  {
    id: 2,
    type: "Дедлайн",
    title: "Заявки на исследовательскую программу MIT",
    desc: "Подайте заявку на летнюю исследовательскую программу MIT до истечения срока.",
    institution: "MIT",
    daysLeft: 6,
    hoursLeft: 12,
    minutesLeft: 0,
    documents: ["Исследовательское предложение", "Академическая выписка", "Рекомендательное письмо"],
    requiredFiles: [
      { icon: "📄", name: "kopiya_pasporta.pdf" },
      { icon: "📝", name: "issledovatelskoe_predlozhenie.pdf" },
      { icon: "🎓", name: "akademicheskaya_vypiska.pdf" },
    ],
  },
  {
    id: 3,
    type: "Стипендия",
    title: "Программа Erasmus+",
    desc: "Учёба в Европе с полным финансированием. Открыто для всех специальностей из университетов Центральной Азии.",
    institution: "Erasmus+",
    daysLeft: 30,
    hoursLeft: 8,
    minutesLeft: 20,
    documents: ["Мотивационное письмо", "Академическая выписка", "Языковой сертификат", "Резюме"],
    requiredFiles: [
      { icon: "📄", name: "kopiya_pasporta.pdf" },
      { icon: "✉️", name: "motivatsionnoe_pismo.pdf" },
      { icon: "🌐", name: "yazykovoy_sertifikat.pdf" },
    ],
  },
  {
    id: 4,
    type: "Дедлайн",
    title: "Подача документов в МГУ",
    desc: "Последний день для отправки всех необходимых документов в Московский государственный университет.",
    institution: "МГУ",
    daysLeft: 2,
    hoursLeft: 5,
    minutesLeft: 30,
    documents: ["Аттестат / Диплом", "Фотографии 3×4", "Медицинская справка"],
    requiredFiles: [
      { icon: "📄", name: "kopiya_pasporta.pdf" },
      { icon: "🎓", name: "attestat.pdf" },
      { icon: "🏥", name: "meditsinskaya_spravka.pdf" },
    ],
  },
  {
    id: 5,
    type: "Стипендия",
    title: "Грант Правительства Китая",
    desc: "Полное покрытие обучения в ведущих университетах Китая. Открыто для всех специальностей.",
    institution: "Правительство Китая",
    daysLeft: 45,
    hoursLeft: 16,
    minutesLeft: 10,
    documents: ["Личное эссе", "Академическая выписка", "Медицинская форма", "Языковой сертификат"],
    requiredFiles: [
      { icon: "📄", name: "kopiya_pasporta.pdf" },
      { icon: "🎓", name: "akademicheskaya_vypiska.pdf" },
      { icon: "🏥", name: "meditsinskaya_forma.pdf" },
      { icon: "🌐", name: "yazykovoy_sertifikat.pdf" },
    ],
  },
];
