import type { Scholarship } from "./types";

export const SCHOLARSHIPS: Scholarship[] = [
  // ── Зарубежные ───────────────────────────────────────────────
  {
    id: 1,
    type: { ru: "Стипендия", en: "Scholarship", tg: "Стипендия" },
    categoryKey: "foreign",
    category: { ru: "Зарубежные", en: "International", tg: "Хориҷӣ" },
    title: "Lester B. Pearson Scholarship",
    desc: {
      ru: "Полное покрытие обучения, проживания, книг и расходов в University of Toronto. Одна из самых престижных стипендий Канады.",
      en: "Full coverage of tuition, accommodation, books and expenses at the University of Toronto. One of the most prestigious scholarships in Canada.",
      tg: "Пардохти пурраи таҳсил, хобгоҳ, китобҳо ва хароҷот дар Донишгоҳи Торонто. Яке аз боэътибортарин стипендияҳои Канада.",
    },
    institution: { ru: "University of Toronto", en: "University of Toronto", tg: "University of Toronto" },
    daysLeft: 120, hoursLeft: 10, minutesLeft: 0,
    documents: {
      ru: ["Рекомендация от школы (номинация)", "Мотивационное письмо", "Академическая выписка", "Резюме"],
      en: ["School recommendation (nomination)", "Motivation letter", "Academic transcript", "CV / Resume"],
      tg: ["Тавсияи мактаб (номинатсия)", "Мактуби ангезавӣ", "Баромади академӣ", "CV / Тарҷумаи ҳол"],
    },
    requiredFiles: [
      { icon: "📄", name: "pasport.pdf" },
      { icon: "🎓", name: "attestat.pdf" },
      { icon: "✉️", name: "nominatsiya_shkoly.pdf" },
    ],
  },
  {
    id: 2,
    type: { ru: "Стипендия", en: "Scholarship", tg: "Стипендия" },
    categoryKey: "foreign",
    category: { ru: "Зарубежные", en: "International", tg: "Хориҷӣ" },
    title: "Erasmus+ Programme",
    desc: {
      ru: "Полное финансирование магистратуры в 2–3 странах Европы. Покрывает обучение, проживание, перелёты, страховку и ~1000–1400€/мес.",
      en: "Full funding for a master's degree in 2–3 European countries. Covers tuition, accommodation, flights, insurance and ~1000–1400€/month.",
      tg: "Маблағгузории пурраи магистратура дар 2–3 кишвари Аврупо. Таҳсил, хобгоҳ, парвоз, суғурта ва ~1000–1400€/моҳ.",
    },
    institution: { ru: "Erasmus+", en: "Erasmus+", tg: "Erasmus+" },
    daysLeft: 90, hoursLeft: 8, minutesLeft: 20,
    documents: {
      ru: ["Мотивационное письмо", "Академическая выписка", "IELTS 6.0+", "Рекомендательные письма (2 шт.)", "CV / Резюме"],
      en: ["Motivation letter", "Academic transcript", "IELTS 6.0+", "Recommendation letters (2)", "CV / Resume"],
      tg: ["Мактуби ангезавӣ", "Баромади академӣ", "IELTS 6.0+", "Мактубҳои тавсиявӣ (2 дона)", "CV / Тарҷумаи ҳол"],
    },
    requiredFiles: [
      { icon: "📄", name: "pasport.pdf" },
      { icon: "🌐", name: "ielts_sertifikat.pdf" },
      { icon: "✉️", name: "motivatsionnoe_pismo.pdf" },
      { icon: "🎓", name: "diplom.pdf" },
    ],
  },
  {
    id: 3,
    type: { ru: "Стипендия", en: "Scholarship", tg: "Стипендия" },
    categoryKey: "foreign",
    category: { ru: "Зарубежные", en: "International", tg: "Хориҷӣ" },
    title: "DAAD Scholarship",
    desc: {
      ru: "Почти полное покрытие обучения в Германии: проживание, ~850–1200€/мес., медицинская страховка. Обучение на английском или немецком.",
      en: "Near-full coverage of studies in Germany: accommodation, ~850–1200€/month, health insurance. Programs in English or German.",
      tg: "Пардохти тақрибан пурраи таҳсил дар Олмон: хобгоҳ, ~850–1200€/моҳ, суғуртаи тиббӣ. Таҳсил ба англисӣ ё олмонӣ.",
    },
    institution: { ru: "DAAD (Германия)", en: "DAAD (Germany)", tg: "DAAD (Олмон)" },
    daysLeft: 75, hoursLeft: 12, minutesLeft: 0,
    documents: {
      ru: ["Мотивационное письмо", "Диплом / аттестат", "IELTS или TestDaF", "Рекомендательные письма", "CV / Резюме"],
      en: ["Motivation letter", "Diploma / Certificate", "IELTS or TestDaF", "Recommendation letters", "CV / Resume"],
      tg: ["Мактуби ангезавӣ", "Диплом / Аттестат", "IELTS ё TestDaF", "Мактубҳои тавсиявӣ", "CV / Тарҷумаи ҳол"],
    },
    requiredFiles: [
      { icon: "📄", name: "pasport.pdf" },
      { icon: "🌐", name: "yazykovoy_sertifikat.pdf" },
      { icon: "✉️", name: "motivatsionnoe_pismo.pdf" },
      { icon: "🎓", name: "diplom.pdf" },
    ],
  },
  {
    id: 4,
    type: { ru: "Стипендия", en: "Scholarship", tg: "Стипендия" },
    categoryKey: "foreign",
    category: { ru: "Зарубежные", en: "International", tg: "Хориҷӣ" },
    title: "Fulbright Program",
    desc: {
      ru: "Полное финансирование учёбы в США: обучение, проживание, перелёт, страховка, ~1000–1500$/мес. Высокая конкуренция — важны лидерство и активность.",
      en: "Full funding for study in the USA: tuition, accommodation, flights, insurance, ~1000–1500$/month. Highly competitive — leadership and activity matter.",
      tg: "Маблағгузории пурраи таҳсил дар ИМА: таҳсил, хобгоҳ, парвоз, суғурта, ~1000–1500$/моҳ. Рақобати баланд — роҳбарӣ ва фаъолият муҳим аст.",
    },
    institution: { ru: "Fulbright (США)", en: "Fulbright (USA)", tg: "Fulbright (ИМА)" },
    daysLeft: 60, hoursLeft: 6, minutesLeft: 30,
    documents: {
      ru: ["Мотивационное эссе", "CV / Резюме", "Рекомендательные письма", "IELTS или TOEFL", "Диплом"],
      en: ["Motivation essay", "CV / Resume", "Recommendation letters", "IELTS or TOEFL", "Diploma"],
      tg: ["Эссеи ангезавӣ", "CV / Тарҷумаи ҳол", "Мактубҳои тавсиявӣ", "IELTS ё TOEFL", "Диплом"],
    },
    requiredFiles: [
      { icon: "📄", name: "pasport.pdf" },
      { icon: "🌐", name: "toefl_ielts.pdf" },
      { icon: "✉️", name: "esse.pdf" },
      { icon: "🎓", name: "diplom.pdf" },
    ],
  },
  {
    id: 5,
    type: { ru: "Стипендия", en: "Scholarship", tg: "Стипендия" },
    categoryKey: "foreign",
    category: { ru: "Зарубежные", en: "International", tg: "Хориҷӣ" },
    title: "Chevening Scholarship",
    desc: {
      ru: "Полное покрытие магистратуры в Великобритании: обучение, проживание, перелёт, виза, ежемесячная стипендия. Требуется опыт работы 2+ года.",
      en: "Full coverage of a master's degree in the UK: tuition, accommodation, flights, visa, monthly stipend. Requires 2+ years of work experience.",
      tg: "Пардохти пурраи магистратура дар Британия: таҳсил, хобгоҳ, парвоз, виза, стипендияи моҳона. Таҷрибаи корӣ 2+ сол лозим аст.",
    },
    institution: { ru: "Chevening (Великобритания)", en: "Chevening (UK)", tg: "Chevening (Британия)" },
    daysLeft: 45, hoursLeft: 18, minutesLeft: 0,
    documents: {
      ru: ["IELTS 6.5+", "CV / Резюме", "Мотивационное письмо (лидерство)", "Диплом", "Подтверждение опыта работы"],
      en: ["IELTS 6.5+", "CV / Resume", "Motivation letter (leadership)", "Diploma", "Work experience proof"],
      tg: ["IELTS 6.5+", "CV / Тарҷумаи ҳол", "Мактуби ангезавӣ (роҳбарӣ)", "Диплом", "Тасдиқи таҷрибаи корӣ"],
    },
    requiredFiles: [
      { icon: "📄", name: "pasport.pdf" },
      { icon: "🌐", name: "ielts.pdf" },
      { icon: "💼", name: "opyt_raboty.pdf" },
      { icon: "🎓", name: "diplom.pdf" },
    ],
  },
  {
    id: 6,
    type: { ru: "Стипендия", en: "Scholarship", tg: "Стипендия" },
    categoryKey: "foreign",
    category: { ru: "Зарубежные", en: "International", tg: "Хориҷӣ" },
    title: "Stipendium Hungaricum",
    desc: {
      ru: "Почти полное покрытие обучения в Венгрии: обучение, общежитие, ~120–200€/мес., медицинская страховка. Доступно для большинства специальностей.",
      en: "Near-full coverage of studies in Hungary: tuition, dormitory, ~120–200€/month, health insurance. Available for most fields of study.",
      tg: "Пардохти тақрибан пурраи таҳсил дар Маҷористон: таҳсил, хобгоҳ, ~120–200€/моҳ, суғуртаи тиббӣ. Барои аксари ихтисосҳо дастрас аст.",
    },
    institution: { ru: "Венгрия", en: "Hungary", tg: "Маҷористон" },
    daysLeft: 30, hoursLeft: 14, minutesLeft: 45,
    documents: {
      ru: ["Аттестат / Диплом", "IELTS (иногда не нужен)", "Мотивационное письмо"],
      en: ["Certificate / Diploma", "IELTS (not always required)", "Motivation letter"],
      tg: ["Аттестат / Диплом", "IELTS (ҳамеша лозим нест)", "Мактуби ангезавӣ"],
    },
    requiredFiles: [
      { icon: "📄", name: "pasport.pdf" },
      { icon: "🎓", name: "attestat_diplom.pdf" },
      { icon: "✉️", name: "motivatsionnoe_pismo.pdf" },
    ],
  },
  {
    id: 7,
    type: { ru: "Стипендия", en: "Scholarship", tg: "Стипендия" },
    categoryKey: "foreign",
    category: { ru: "Зарубежные", en: "International", tg: "Хориҷӣ" },
    title: "Chinese Government Scholarship (CSC)",
    desc: {
      ru: "Полное покрытие обучения в Китае: проживание, ~250–500$/мес., медицинская страховка. IELTS не всегда нужен. Сильные IT, медицина, инженерия.",
      en: "Full coverage of studies in China: accommodation, ~250–500$/month, health insurance. IELTS not always required. Strong IT, medicine, engineering programs.",
      tg: "Пардохти пурраи таҳсил дар Чин: хобгоҳ, ~250–500$/моҳ, суғуртаи тиббӣ. IELTS ҳамеша лозим нест. IT, тиб, муҳандисии қавӣ.",
    },
    institution: { ru: "Правительство Китая", en: "Chinese Government", tg: "Ҳукумати Чин" },
    daysLeft: 55, hoursLeft: 16, minutesLeft: 10,
    documents: {
      ru: ["Диплом / аттестат", "Медицинская справка", "Мотивационное письмо"],
      en: ["Diploma / Certificate", "Medical certificate", "Motivation letter"],
      tg: ["Диплом / Аттестат", "Маълумотномаи тиббӣ", "Мактуби ангезавӣ"],
    },
    requiredFiles: [
      { icon: "📄", name: "pasport.pdf" },
      { icon: "🎓", name: "diplom.pdf" },
      { icon: "🏥", name: "meditsinskaya_spravka.pdf" },
    ],
  },
  {
    id: 8,
    type: { ru: "Стипендия", en: "Scholarship", tg: "Стипендия" },
    categoryKey: "foreign",
    category: { ru: "Зарубежные", en: "International", tg: "Хориҷӣ" },
    title: "Global Korea Scholarship (GKS)",
    desc: {
      ru: "Полное финансирование в Южной Корее: обучение, перелёт, проживание, ~800–1000$/мес. + год языкового курса. Можно без знания корейского вначале.",
      en: "Full funding in South Korea: tuition, flights, accommodation, ~800–1000$/month + one year of Korean language training. Korean not required initially.",
      tg: "Маблағгузории пурра дар Кореяи Ҷанубӣ: таҳсил, парвоз, хобгоҳ, ~800–1000$/моҳ + як соли омӯзиши забони корейӣ. Дар аввал корейӣ лозим нест.",
    },
    institution: { ru: "Южная Корея", en: "South Korea", tg: "Кореяи Ҷанубӣ" },
    daysLeft: 40, hoursLeft: 9, minutesLeft: 0,
    documents: {
      ru: ["Диплом / аттестат", "IELTS (не всегда обязателен)", "Мотивационное письмо", "Рекомендательные письма"],
      en: ["Diploma / Certificate", "IELTS (not always required)", "Motivation letter", "Recommendation letters"],
      tg: ["Диплом / Аттестат", "IELTS (ҳамеша лозим нест)", "Мактуби ангезавӣ", "Мактубҳои тавсиявӣ"],
    },
    requiredFiles: [
      { icon: "📄", name: "pasport.pdf" },
      { icon: "🎓", name: "diplom.pdf" },
      { icon: "✉️", name: "motivatsionnoe_pismo.pdf" },
    ],
  },
  {
    id: 9,
    type: { ru: "Стипендия", en: "Scholarship", tg: "Стипендия" },
    categoryKey: "foreign",
    category: { ru: "Зарубежные", en: "International", tg: "Хориҷӣ" },
    title: "Türkiye Scholarships",
    desc: {
      ru: "Полное покрытие обучения в Турции: проживание, перелёт, страховка, ~150–300$/мес. + год турецкого языка. IELTS не нужен.",
      en: "Full coverage of studies in Turkey: accommodation, flights, insurance, ~150–300$/month + one year of Turkish language training. No IELTS required.",
      tg: "Пардохти пурраи таҳсил дар Туркия: хобгоҳ, парвоз, суғурта, ~150–300$/моҳ + як соли омӯзиши турки. IELTS лозим нест.",
    },
    institution: { ru: "Турция", en: "Turkey", tg: "Туркия" },
    daysLeft: 20, hoursLeft: 5, minutesLeft: 30,
    documents: {
      ru: ["Аттестат / Диплом", "Мотивационное письмо", "Рекомендации (иногда)"],
      en: ["Certificate / Diploma", "Motivation letter", "Recommendations (sometimes)"],
      tg: ["Аттестат / Диплом", "Мактуби ангезавӣ", "Тавсияҳо (баъзан)"],
    },
    requiredFiles: [
      { icon: "📄", name: "pasport.pdf" },
      { icon: "🎓", name: "attestat_diplom.pdf" },
      { icon: "✉️", name: "motivatsionnoe_pismo.pdf" },
    ],
  },

  // ── Местные ──────────────────────────────────────────────────
  {
    id: 10,
    type: { ru: "Стипендия", en: "Scholarship", tg: "Стипендия" },
    categoryKey: "local",
    category: { ru: "Местные", en: "Local", tg: "Маҳаллӣ" },
    title: "Президентская стипендия «Дурахшандагон»",
    desc: {
      ru: "Главная государственная стипендия Таджикистана для учёбы за рубежом. Полное финансирование: обучение, перелёт, проживание, стипендия. Сайт: cip.tj",
      en: "Tajikistan's main state scholarship for study abroad. Full funding: tuition, flights, accommodation, stipend. Website: cip.tj",
      tg: "Стипендияи асосии давлатии Тоҷикистон барои таҳсил дар хориҷ. Маблағгузории пурра: таҳсил, парвоз, хобгоҳ, стипендия. Сайт: cip.tj",
    },
    institution: {
      ru: "Центр международных программ РТ",
      en: "International Programs Center of RT",
      tg: "Маркази барномаҳои байналмилалии ҶТ",
    },
    daysLeft: 150, hoursLeft: 0, minutesLeft: 0,
    documents: {
      ru: ["Заявление", "Диплом / аттестат с отличными оценками", "Языковой сертификат", "Медицинская справка"],
      en: ["Application form", "Diploma / Certificate with excellent grades", "Language certificate", "Medical certificate"],
      tg: ["Ариза", "Диплом / Аттестат бо баҳоҳои олӣ", "Сертификати забонӣ", "Маълумотномаи тиббӣ"],
    },
    requiredFiles: [
      { icon: "📄", name: "pasport.pdf" },
      { icon: "🎓", name: "diplom.pdf" },
      { icon: "🌐", name: "yazykovoy_sertifikat.pdf" },
      { icon: "🏥", name: "meditsinskaya_spravka.pdf" },
    ],
  },
  {
    id: 11,
    type: { ru: "Стипендия", en: "Scholarship", tg: "Стипендия" },
    categoryKey: "local",
    category: { ru: "Местные", en: "Local", tg: "Маҳаллӣ" },
    title: "Государственная академическая стипендия",
    desc: {
      ru: "Ежемесячные выплаты студентам бюджетных вузов Таджикистана: ~120–1130 сомони в зависимости от успеваемости. Назначается автоматически после сессии.",
      en: "Monthly payments to students at publicly-funded universities in Tajikistan: ~120–1130 somoni depending on academic performance. Assigned automatically after exams.",
      tg: "Пардохти моҳона ба донишҷӯёни донишгоҳҳои буҷетии Тоҷикистон: ~120–1130 сомонӣ вобаста ба пешрафти таҳсил. Пас аз сессия ба таври худкор таъин мешавад.",
    },
    institution: {
      ru: "Министерство науки и образования РТ",
      en: "Ministry of Education and Science of RT",
      tg: "Вазорати маориф ва илми ҶТ",
    },
    daysLeft: 365, hoursLeft: 0, minutesLeft: 0,
    documents: {
      ru: ["Зачётная книжка с оценками"],
      en: ["Grade transcript"],
      tg: ["Китобчаи зачёт бо баҳоҳо"],
    },
    requiredFiles: [
      { icon: "📄", name: "zachyotnaya_knizhka.pdf" },
    ],
  },
  {
    id: 12,
    type: { ru: "Стипендия", en: "Scholarship", tg: "Стипендия" },
    categoryKey: "local",
    category: { ru: "Местные", en: "Local", tg: "Маҳаллӣ" },
    title: "Международная президентская стипендия (закон РТ)",
    desc: {
      ru: "Полное финансирование обучения за рубежом по специальностям, определённым потребностями экономики Таджикистана. Дедлайн совпадает с «Дурахшандагон».",
      en: "Full funding for study abroad in fields determined by Tajikistan's economic needs. Deadline coincides with Durakhshandagon.",
      tg: "Маблағгузории пурраи таҳсил дар хориҷ мутобиқ ба ихтисосҳои муайяншудаи иқтисоди Тоҷикистон. Мӯҳлат бо «Дурахшандагон» якхела аст.",
    },
    institution: {
      ru: "Центр международных программ РТ",
      en: "International Programs Center of RT",
      tg: "Маркази барномаҳои байналмилалии ҶТ",
    },
    daysLeft: 150, hoursLeft: 0, minutesLeft: 0,
    documents: {
      ru: ["Заявление", "Диплом / аттестат", "Языковой сертификат"],
      en: ["Application form", "Diploma / Certificate", "Language certificate"],
      tg: ["Ариза", "Диплом / Аттестат", "Сертификати забонӣ"],
    },
    requiredFiles: [
      { icon: "📄", name: "pasport.pdf" },
      { icon: "🎓", name: "diplom.pdf" },
      { icon: "🌐", name: "yazykovoy_sertifikat.pdf" },
    ],
  },
  {
    id: 13,
    type: { ru: "Стипендия", en: "Scholarship", tg: "Стипендия" },
    categoryKey: "local",
    category: { ru: "Местные", en: "Local", tg: "Маҳаллӣ" },
    title: "DAFI Scholarship (УВКБ ООН)",
    desc: {
      ru: "Почти полное покрытие обучения в вузах Таджикистана до 4 лет. Только для беженцев и соискателей убежища. Дедлайн обычно в июне.",
      en: "Near-full coverage of studies at Tajikistan universities for up to 4 years. For refugees and asylum seekers only. Deadline usually in June.",
      tg: "Пардохти тақрибан пурраи таҳсил дар донишгоҳҳои Тоҷикистон то 4 сол. Танҳо барои паноҳандагон. Мӯҳлат одатан дар июн.",
    },
    institution: { ru: "УВКБ ООН / Таджикистан", en: "UNHCR / Tajikistan", tg: "КОБПАОО / Тоҷикистон" },
    daysLeft: 60, hoursLeft: 0, minutesLeft: 0,
    documents: {
      ru: ["Документ беженца / соискателя убежища", "Аттестат", "Заявление"],
      en: ["Refugee / asylum seeker document", "Certificate", "Application form"],
      tg: ["Ҳуҷҷати паноҳанда", "Аттестат", "Ариза"],
    },
    requiredFiles: [
      { icon: "📄", name: "dokument_bezhentsa.pdf" },
      { icon: "🎓", name: "attestat.pdf" },
    ],
  },
  {
    id: 14,
    type: { ru: "Дедлайн", en: "Deadline", tg: "Мӯҳлат" },
    categoryKey: "local",
    category: { ru: "Местные", en: "Local", tg: "Маҳаллӣ" },
    title: "Государственный образовательный грант (НЦТ)",
    desc: {
      ru: "Полностью бесплатное обучение в вузах Таджикистана для победителей тестирования НЦТ. Самый доступный вариант — подаётся через поступление летом.",
      en: "Fully free education at Tajikistan universities for winners of the NCT exam. The most accessible option — applied through summer admissions.",
      tg: "Таҳсили комилан ройгон дар донишгоҳҳои Тоҷикистон барои ғолибони санҷиши МКТ. Дастрастарин вариант — тавассути қабули тобистона.",
    },
    institution: { ru: "НЦТ / Вузы Таджикистана", en: "NCT / Universities of Tajikistan", tg: "МКТ / Донишгоҳҳои Тоҷикистон" },
    daysLeft: 70, hoursLeft: 10, minutesLeft: 0,
    documents: {
      ru: ["Аттестат", "Результаты НЦТ", "Медицинская справка", "Фотографии 3×4"],
      en: ["Certificate", "NCT results", "Medical certificate", "Photos 3×4"],
      tg: ["Аттестат", "Натиҷаҳои МКТ", "Маълумотномаи тиббӣ", "Акс 3×4"],
    },
    requiredFiles: [
      { icon: "📄", name: "pasport.pdf" },
      { icon: "🎓", name: "attestat.pdf" },
      { icon: "🏥", name: "meditsinskaya_spravka.pdf" },
    ],
  },
];
